<?php
/*
 * Copyright 2014-2025 GPLv3, Open Crypto Tracker by Mike Kilday: Mike@DragonFrugal.com (leave this copyright / attribution intact in ALL forks / copies!)
 */


//////////////////////////////////////////////////
// SECONDARY VARS
//////////////////////////////////////////////////


// For check / auto-correct of MANDATORY plugin settings
$ct['plugin_runtime_mode_check'] = array(
                                       'cron',
                                       'webhook',
                                       'ui',
                                       'all',
                                       );
                                  

// Country locales, for number formatting           
$ct['country_locales'] = array(
                         'af-ZA' => 'Afrikaans (South Africa)',
                         'am-ET' => 'Amharic (Ethiopia)',
                         'ar-AE' => 'Arabic (United Arab Emirates)',
                         'ar-BH' => 'Arabic (Bahrain)',
                         'ar-DZ' => 'Arabic (Algeria)',
                         'ar-EG' => 'Arabic (Egypt)',
                         'ar-IQ' => 'Arabic (Iraq)',
                         'ar-JO' => 'Arabic (Jordan)',
                         'ar-KW' => 'Arabic (Kuwait)',
                         'ar-LB' => 'Arabic (Lebanon)',
                         'ar-LY' => 'Arabic (Libya)',
                         'ar-MA' => 'Arabic (Morocco)',
                         'ar-OM' => '	Arabic (Oman)',
                         'ar-QA' => 'Arabic (Qatar)',
                         'ar-SA' => 'Arabic (Saudi Arabia)',
                         'ar-SD' => 'Arabic (Sudan)',
                         'ar-SY' => 'Arabic (Syria)',
                         'ar-TN' => 'Arabic (Tunisia)',
                         'ar-YE' => 'Arabic (Yemen)',
                         'as-IN' => 'Assamese (India)',
                         'az-Cyrl-AZ' => 'Azerbaijani (Cyrillic, Azerbaijan)',
                         'az-Latn-AZ' => 'Azerbaijani (Latin, Azerbaijan)',
                         'be-BY' => 'Belarusian (Belarus)',
                         'bg-BG' => 'Bulgarian (Bulgaria)',
                         'bn-BD' => 'Bangla (Bangladesh)',
                         'bn-IN' => 'Bangla (India)',
                         'bo-CN' => 'Tibetan (China)',
                         'br-FR' => 'Breton (France)',
                         'bs-Cyrl-BA' => 'Bosnian (Cyrillic, Bosnia & Herzegovina)',
                         'bs-Latn-BA' => 'Bosnian (Latin, Bosnia & Herzegovina)',
                         'ca-ES' => 'Catalan (Spain)',
                         'cs-CZ' => 'Czech (Czechia)',
                         'cy-GB' => 'Welsh (United Kingdom)',
                         'da-DK' => 'Danish (Denmark)',
                         'de-AT' => 'German (Austria)',
                         'de-CH' => 'German (Switzerland)',
                         'de-DE' => 'German (Germany)',
                         'de-LI' => 'German (Liechtenstein)',
                         'de-LU' => 'German (Luxembourg)',
                         'dsb-DE' => 'Lower Sorbian (Germany)',
                         'el-CY' => 'Greek (Cyprus)',
                         'el-GR' => 'Greek (Greece)',
                         'en-AU' => 'English (Australia)',
                         'en-BZ' => 'English (Belize)',
                         'en-CA' => 'English (Canada)',
                         'en-GB' => 'English (United Kingdom)',
                         'en-IE' => 'English (Ireland)',
                         'en-IN' => 'English (India)',
                         'en-JM' => 'English (Jamaica)',
                         'en-MT' => 'English (Malta)',
                         'en-MY' => 'English (Malaysia) ',
                         'en-NZ' => 'English (New Zealand)',
                         'en-PH' => 'English (Philippines)',
                         'en-SG' => 'English (Singapore)',
                         'en-TT' => 'English (Trinidad & Tobago)',
                         'en-US' => 'English (United States)',
                         'en-ZA' => 'English (South Africa)',
                         'en-ZW' => 'English (Zimbabwe)',
                         'es-AR' => 'UI_DESC',
                         'es-BO' => 'UI_DESC',
                         'es-CL' => 'UI_DESC',
                         'es-CO' => 'UI_DESC',
                         'es-CR' => 'UI_DESC',
                         'es-DO' => 'UI_DESC',
                         'es-EC' => 'UI_DESC',
                         'es-ES' => 'UI_DESC',
                         'es-GT' => 'UI_DESC',
                         'es-HN' => 'UI_DESC',
                         'es-MX' => 'UI_DESC',
                         'es-NI' => 'UI_DESC',
                         'es-PA' => 'UI_DESC',
                         'es-PE' => 'UI_DESC',
                         'es-PR' => 'UI_DESC',
                         'es-PY' => 'UI_DESC',
                         'es-SV' => 'UI_DESC',
                         'es-US' => 'UI_DESC',
                         'es-UY' => 'UI_DESC',
                         'es-VE' => 'UI_DESC',
                         'et-EE' => 'UI_DESC',
                         'eu-ES' => 'UI_DESC',
                         'fa-IR' => 'UI_DESC',
                         'fi-FI' => 'UI_DESC',
                         'fil-PH' => 'UI_DESC',
                         'fo-FO' => 'UI_DESC',
                         'fr-BE' => 'UI_DESC',
                         'fr-CA' => 'UI_DESC',
                         'fr-CH' => 'UI_DESC',
                         'fr-FR' => 'UI_DESC',
                         'fr-LU' => 'UI_DESC',
                         'fr-MC' => 'UI_DESC',
                         'fy-NL' => 'UI_DESC',
                         'ga-IE' => 'UI_DESC',
                         'gd-GB' => 'UI_DESC',
                         'gd-ie' => 'UI_DESC',
                         'gl-ES' => 'UI_DESC',
                         'gsw-FR' => 'UI_DESC',
                         'gu-IN' => 'UI_DESC',
                         'ha-Latn-NG' => 'UI_DESC',
                         'he-IL' => 'UI_DESC',
                         'hi-IN' => 'UI_DESC',
                         'hr-BA' => 'UI_DESC',
                         'hr-HR' => 'UI_DESC',
                         'hsb-DE' => 'UI_DESC',
                         'hu-HU' => 'UI_DESC',
                         'hy-AM' => 'UI_DESC',
                         'id-ID' => 'UI_DESC',
                         'ig-NG' => 'UI_DESC',
                         'ii-CN' => 'UI_DESC',
                         'in-ID' => 'UI_DESC',
                         'is-IS' => 'UI_DESC',
                         'it-CH' => 'UI_DESC',
                         'it-IT' => 'UI_DESC',
                         'iu-Cans-CA' => 'UI_DESC',
                         'iu-Latn-CA' => 'UI_DESC',
                         'iw-IL' => 'UI_DESC',
                         'ja-JP' => 'UI_DESC',
                         'ka-GE' => 'UI_DESC',
                         'kk-KZ' => 'UI_DESC',
                         'kl-GL' => 'UI_DESC',
                         'km-KH' => 'UI_DESC',
                         'kn-IN' => 'UI_DESC',
                         'kok-IN' => 'UI_DESC',
                         'ko-KR' => 'UI_DESC',
                         'ky-KG' => 'UI_DESC',
                         'lb-LU' => 'UI_DESC',
                         'lo-LA' => 'UI_DESC',
                         'lt-LT' => 'UI_DESC',
                         'lv-LV' => 'UI_DESC',
                         'mi-NZ' => 'UI_DESC',
                         'mk-MK' => 'UI_DESC',
                         'ml-IN' => 'UI_DESC',
                         'mn-MN' => 'UI_DESC',
                         'mn-Mong-CN' => 'UI_DESC',
                         'moh-CA' => 'UI_DESC',
                         'mr-IN' => 'UI_DESC',
                         'ms-BN' => 'UI_DESC',
                         'ms-MY' => 'UI_DESC',
                         'mt-MT' => 'UI_DESC',
                         'nb-NO' => 'UI_DESC',
                         'ne-NP' => 'UI_DESC',
                         'nl-BE' => 'UI_DESC',
                         'nl-NL' => 'UI_DESC',
                         'nn-NO' => 'UI_DESC',
                         'no-no' => 'UI_DESC',
                         'nso-ZA' => 'UI_DESC',
                         'oc-FR' => 'UI_DESC',
                         'or-IN' => 'UI_DESC',
                         'pa-IN' => 'UI_DESC',
                         'pl-PL' => 'UI_DESC',
                         'prs-AF' => 'UI_DESC',
                         'ps-AF' => 'UI_DESC',
                         'pt-BR' => 'UI_DESC',
                         'pt-PT' => 'UI_DESC',
                         'qut-GT' => 'UI_DESC',
                         'quz-BO' => 'UI_DESC',
                         'quz-EC' => 'UI_DESC',
                         'quz-PE' => 'UI_DESC',
                         'rm-CH' => 'UI_DESC',
                         'ro-mo' => 'UI_DESC',
                         'ro-RO' => 'UI_DESC',
                         'ru-mo' => 'UI_DESC',
                         'ru-RU' => 'UI_DESC',
                         'rw-RW' => 'UI_DESC',
                         'sah-RU' => 'UI_DESC',
                         'sa-IN' => 'UI_DESC',
                         'se-FI' => 'UI_DESC',
                         'se-NO' => 'UI_DESC',
                         'se-SE' => 'UI_DESC',
                         'si-LK' => 'UI_DESC',
                         'sk-SK' => 'UI_DESC',
                         'sl-SI' => 'UI_DESC',
                         'sma-NO' => 'UI_DESC',
                         'sma-SE' => 'UI_DESC',
                         'smj-NO' => 'UI_DESC',
                         'smj-SE' => 'UI_DESC',
                         'smn-FI' => 'UI_DESC',
                         'sms-FI' => 'UI_DESC',
                         'sq-AL' => 'UI_DESC',
                         'sr-BA' => 'UI_DESC',
                         'sr-CS' => 'UI_DESC',
                         'sr-Cyrl-BA' => 'UI_DESC',
                         'sr-Cyrl-CS' => 'UI_DESC',
                         'sr-Cyrl-ME' => 'UI_DESC',
                         'sr-Cyrl-RS' => 'UI_DESC',
                         'sr-Latn-BA' => 'UI_DESC',
                         'sr-Latn-CS' => 'UI_DESC',
                         'sr-Latn-ME' => 'UI_DESC',
                         'sr-Latn-RS' => 'UI_DESC',
                         'sr-ME' => 'UI_DESC',
                         'sr-RS' => 'UI_DESC',
                         'sr-sp' => 'UI_DESC',
                         'sv-FI' => 'UI_DESC',
                         'sv-SE' => 'UI_DESC',
                         'sw-KE' => 'UI_DESC',
                         'syr-SY' => 'UI_DESC',
                         'ta-IN' => 'UI_DESC',
                         'te-IN' => 'UI_DESC',
                         'tg-Cyrl-TJ' => 'UI_DESC',
                         'th-TH' => 'UI_DESC',
                         'tk-TM' => 'UI_DESC',
                         'tlh-QS' => 'UI_DESC',
                         'tn-ZA' => 'UI_DESC',
                         'tr-TR' => 'UI_DESC',
                         'tt-RU' => 'UI_DESC',
                         'tzm-Latn-DZ' => 'UI_DESC',
                         'ug-CN' => 'UI_DESC',
                         'uk-UA' => 'UI_DESC',
                         'ur-PK' => 'UI_DESC',
                         'uz-Cyrl-UZ' => 'UI_DESC',
                         'uz-Latn-UZ' => 'UI_DESC',
                         'uz-uz' => 'UI_DESC',
                         'vi-VN' => 'UI_DESC',
                         'wo-SN' => 'UI_DESC',
                         'xh-ZA' => 'UI_DESC',
                         'yo-NG' => 'UI_DESC',
                         'zh-CN' => 'UI_DESC',
                         'zh-HK' => 'UI_DESC',
                         'zh-MO' => 'UI_DESC',
                         'zh-SG' => 'UI_DESC',
                         'zh-TW' => 'UI_DESC',
                         'zu-ZA' => 'UI_DESC',
                         );

$ct['usort_alpha'] = false; // NOT sorting by subkey value
// uasort (instead of usort) maintains the associations of the (NON-numeric) keys
uasort($ct['country_locales'], array($ct['gen'], 'usort_alpha') );


////////////////////////////////////////////////////////////
// END SECONDARY VARS
////////////////////////////////////////////////////////////

// DON'T LEAVE ANY WHITESPACE AFTER THE CLOSING PHP TAG!
 
?>