<?php
/*
 * Copyright 2014-2026 GPLv3, Open Crypto Tracker by Mike Kilday: Mike@DragonFrugal.com (leave this copyright / attribution intact in ALL forks / copies!)
 */


//////////////////////////////////////////////////
// SECONDARY VARS
//////////////////////////////////////////////////


// For check / auto-correct of MANDATORY plugin settings
$ct['plugin_runtime_mode_check'] = array(
                                       'cron',
                                       'webhook',
                                       'ui',
                                       'all',
                                       );
                                  

// Country locales, for number formatting           
$ct['country_locales'] = array(
                         'af-ZA' => 'Afrikaans (South Africa)',
                         'am-ET' => 'Amharic (Ethiopia)',
                         'ar-AE' => 'Arabic (United Arab Emirates)',
                         'ar-BH' => 'Arabic (Bahrain)',
                         'ar-DZ' => 'Arabic (Algeria)',
                         'ar-EG' => 'Arabic (Egypt)',
                         'ar-IQ' => 'Arabic (Iraq)',
                         'ar-JO' => 'Arabic (Jordan)',
                         'ar-KW' => 'Arabic (Kuwait)',
                         'ar-LB' => 'Arabic (Lebanon)',
                         'ar-LY' => 'Arabic (Libya)',
                         'ar-MA' => 'Arabic (Morocco)',
                         'ar-OM' => '	Arabic (Oman)',
                         'ar-QA' => 'Arabic (Qatar)',
                         'ar-SA' => 'Arabic (Saudi Arabia)',
                         'ar-SD' => 'Arabic (Sudan)',
                         'ar-SY' => 'Arabic (Syria)',
                         'ar-TN' => 'Arabic (Tunisia)',
                         'ar-YE' => 'Arabic (Yemen)',
                         'as-IN' => 'Assamese (India)',
                         'az-Cyrl-AZ' => 'Azerbaijani (Cyrillic, Azerbaijan)',
                         'az-Latn-AZ' => 'Azerbaijani (Latin, Azerbaijan)',
                         'be-BY' => 'Belarusian (Belarus)',
                         'bg-BG' => 'Bulgarian (Bulgaria)',
                         'bn-BD' => 'Bangla (Bangladesh)',
                         'bn-IN' => 'Bangla (India)',
                         'bo-CN' => 'Tibetan (China)',
                         'br-FR' => 'Breton (France)',
                         'bs-Cyrl-BA' => 'Bosnian (Cyrillic, Bosnia & Herzegovina)',
                         'bs-Latn-BA' => 'Bosnian (Latin, Bosnia & Herzegovina)',
                         'ca-ES' => 'Catalan (Spain)',
                         'cs-CZ' => 'Czech (Czechia)',
                         'cy-GB' => 'Welsh (United Kingdom)',
                         'da-DK' => 'Danish (Denmark)',
                         'de-AT' => 'German (Austria)',
                         'de-CH' => 'German (Switzerland)',
                         'de-DE' => 'German (Germany)',
                         'de-LI' => 'German (Liechtenstein)',
                         'de-LU' => 'German (Luxembourg)',
                         'dsb-DE' => 'Lower Sorbian (Germany)',
                         'el-CY' => 'Greek (Cyprus)',
                         'el-GR' => 'Greek (Greece)',
                         'en-AU' => 'English (Australia)',
                         'en-BZ' => 'English (Belize)',
                         'en-CA' => 'English (Canada)',
                         'en-GB' => 'English (United Kingdom)',
                         'en-IE' => 'English (Ireland)',
                         'en-IN' => 'English (India)',
                         'en-JM' => 'English (Jamaica)',
                         'en-MT' => 'English (Malta)',
                         'en-MY' => 'English (Malaysia) ',
                         'en-NZ' => 'English (New Zealand)',
                         'en-PH' => 'English (Philippines)',
                         'en-SG' => 'English (Singapore)',
                         'en-TT' => 'English (Trinidad & Tobago)',
                         'en-US' => 'English (United States)',
                         'en-ZA' => 'English (South Africa)',
                         'en-ZW' => 'English (Zimbabwe)',
                         'es-AR' => 'Spanish (Argentina)',
                         'es-BO' => 'Spanish (Bolivia)',
                         'es-CL' => 'Spanish (Chile)',
                         'es-CO' => 'Spanish (Colombia)',
                         'es-CR' => 'Spanish (Costa Rica)',
                         'es-DO' => 'Spanish (Dominican Republic)',
                         'es-EC' => 'Spanish (Ecuador)',
                         'es-ES' => 'Spanish (Spain)',
                         'es-GT' => 'Spanish (Guatemala)',
                         'es-HN' => 'Spanish (Honduras)',
                         'es-MX' => 'Spanish (Mexico)',
                         'es-NI' => 'Spanish (Nicaragua)',
                         'es-PA' => 'Spanish (Panama)',
                         'es-PE' => 'Spanish (Peru)',
                         'es-PR' => 'Spanish (Puerto Rico)',
                         'es-PY' => 'Spanish (Paraguay)',
                         'es-SV' => 'Spanish (El Salvador)',
                         'es-US' => 'Spanish (United States)',
                         'es-UY' => 'Spanish (Uruguay)',
                         'es-VE' => 'Spanish (Venezuela)',
                         'et-EE' => 'Estonian (Estonia)',
                         'eu-ES' => 'Basque (Spain)',
                         'fa-IR' => 'Persian (Iran)',
                         'fi-FI' => 'Finnish (Finland)',
                         'fil-PH' => 'Filipino (Philippines)',
                         'fo-FO' => 'Faroese (Faroe Islands)',
                         'fr-BE' => 'French (Belgium)',
                         'fr-CA' => 'French (Canada)',
                         'fr-CH' => 'French (Switzerland)',
                         'fr-FR' => 'French (France)',
                         'fr-LU' => 'French (Luxembourg)',
                         'fr-MC' => 'French (Monaco)',
                         'fy-NL' => 'Western Frisian (Netherlands)',
                         'ga-IE' => 'Irish (Ireland)',
                         'gd-GB' => 'Scottish Gaelic (United Kingdom)',
                         'gl-ES' => 'Galician (Spain)',
                         'gsw-FR' => 'Swiss German (France)',
                         'gu-IN' => 'Gujarati (India)',
                         'he-IL' => 'Hebrew (Israel)',
                         'hi-IN' => 'Hindi (India)',
                         'hr-BA' => 'Croatian (Bosnia & Herzegovina)',
                         'hr-HR' => 'Croatian (Croatia)',
                         'hsb-DE' => 'Upper Sorbian (Germany)',
                         'hu-HU' => 'Hungarian (Hungary)',
                         'hy-AM' => 'Armenian (Armenia)',
                         'id-ID' => 'Indonesian (Indonesia)',
                         'ig-NG' => 'Igbo (Nigeria)',
                         'ii-CN' => 'Sichuan Yi (China)',
                         'is-IS' => 'Icelandic (Iceland)',
                         'it-CH' => 'Italian (Switzerland)',
                         'it-IT' => 'Italian (Italy)',
                         'ja-JP' => 'Japanese (Japan)',
                         'ka-GE' => 'Georgian (Georgia)',
                         'kk-KZ' => 'Kazakh (Kazakhstan)',
                         'kl-GL' => 'Kalaallisut (Greenland)',
                         'km-KH' => 'Khmer (Cambodia)',
                         'kn-IN' => 'Kannada (India)',
                         'kok-IN' => 'Konkani (India)',
                         'ko-KR' => 'Korean (South Korea)',
                         'ky-KG' => 'Kyrgyz (Kyrgyzstan)',
                         'lb-LU' => 'Luxembourgish (Luxembourg)',
                         'lo-LA' => 'Lao (Laos)',
                         'lt-LT' => 'Lithuanian (Lithuania)',
                         'lv-LV' => 'Latvian (Latvia)',
                         'mk-MK' => 'Macedonian (Macedonia)',
                         'ml-IN' => 'Malayalam (India)',
                         'mn-MN' => 'Mongolian (Mongolia)',
                         'mr-IN' => 'Marathi (India)',
                         'ms-BN' => 'Malay (Brunei)',
                         'ms-MY' => 'Malay (Malaysia)',
                         'mt-MT' => 'Maltese (Malta)',
                         'nb-NO' => 'Norwegian Bokmål (Norway)',
                         'ne-NP' => 'Nepali (Nepal)',
                         'nl-BE' => 'Dutch (Belgium)',
                         'nl-NL' => 'Dutch (Netherlands)',
                         'nn-NO' => 'Norwegian Nynorsk (Norway)',
                         'or-IN' => 'Odia (India)',
                         'pl-PL' => 'Polish (Poland)',
                         'ps-AF' => 'Pashto (Afghanistan)',
                         'pt-BR' => 'Portuguese (Brazil)',
                         'pt-PT' => 'Portuguese (Portugal)',
                         'rm-CH' => 'Romansh (Switzerland)',
                         'ro-RO' => 'Romanian (Romania)',
                         'ru-RU' => 'Russian (Russia)',
                         'rw-RW' => 'Kinyarwanda (Rwanda)',
                         'sah-RU' => 'Sakha (Russia)',
                         'se-FI' => 'Northern Sami (Finland)',
                         'se-NO' => 'Northern Sami (Norway)',
                         'se-SE' => 'Northern Sami (Sweden)',
                         'si-LK' => 'Sinhala (Sri Lanka)',
                         'sk-SK' => 'Slovak (Slovakia)',
                         'sl-SI' => 'Slovenian (Slovenia)',
                         'smn-FI' => 'Inari Sami (Finland)',
                         'sq-AL' => 'Albanian (Albania)',
                         'sr-Cyrl-BA' => 'Serbian (Cyrillic, Bosnia & Herzegovina)',
                         'sr-Cyrl-ME' => 'Serbian (Cyrillic, Montenegro)',
                         'sr-Cyrl-RS' => 'Serbian (Cyrillic, Serbia)',
                         'sr-Latn-BA' => 'Serbian (Latin, Bosnia & Herzegovina)',
                         'sr-Latn-ME' => 'Serbian (Latin, Montenegro)',
                         'sr-Latn-RS' => 'Serbian (Latin, Serbia)',
                         'sv-FI' => 'Swedish (Finland)',
                         'sv-SE' => 'Swedish (Sweden)',
                         'sw-KE' => 'Swahili (Kenya)',
                         'ta-IN' => 'Tamil (India)',
                         'te-IN' => 'Telugu (India)',
                         'th-TH' => 'Thai (Thailand)',
                         'tr-TR' => 'Turkish (Turkey)',
                         'tt-RU' => 'Tatar (Russia)',
                         'ug-CN' => 'Uyghur (China)',
                         'uk-UA' => 'Ukrainian (Ukraine)',
                         'ur-PK' => 'Urdu (Pakistan)',
                         'uz-Cyrl-UZ' => 'Uzbek (Cyrillic, Uzbekistan)',
                         'uz-Latn-UZ' => 'Uzbek (Latin, Uzbekistan)',
                         'vi-VN' => 'Vietnamese (Vietnam)',
                         'wo-SN' => 'Wolof (Senegal)',
                         'yo-NG' => 'Yoruba (Nigeria)',
                         'zh-Hans-CN' => 'Chinese (Simplified, China)',
                         'zh-Hans-HK' => 'Chinese (Simplified, Hong Kong SAR China)',
                         'zh-Hans-SG' => 'Chinese (Simplified, Singapore)',
                         'zh-Hant-TW' => 'Chinese (Traditional, Taiwan)',
                         'zu-ZA' => 'Zulu (South Africa)',
                         );

// $ct['sort_by_nested'] does NOT need to be set (CAN BE DEFAULT [false]),
// as this is NOT a multidimensional (nested) array structure
// uasort (instead of usort) maintains the associations of the (NON-numeric) ROOT keys
uasort($ct['country_locales'], array($ct['var'], 'usort_asc') );


////////////////////////////////////////////////////////////
// END SECONDARY VARS
////////////////////////////////////////////////////////////

// DON'T LEAVE ANY WHITESPACE AFTER THE CLOSING PHP TAG!
 
?>